server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    virtual-host: /leyou
    username: /leyou
    password: leyou
    host: 192.168.19.121

leyou:
  sms:
    accessKeyId: LTAI4GFv7HUFnXmbUwMN21gV # 你自己的accessKeyId
    accessKeySecret: dhCAkjjFvRS6eU4fK6m2TJEF2FS8sH # 你自己的AccessKeySecret
    signName: 易悠商城 # 签名名称
    verifyCodeTemplate: SMS_205135848 # 模板名称
